exclude:
  - .github
  - .gitignore
  - CNAME
  - CODE_OF_CONDUCT.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
plugins:
  - jekyll-feed
title: Kevin Newton
author: Kevin Newton
url: https://kddnewton.com
